// Copies ABIs and the selected local deployment into the checked-in frontend snapshot.
// Run after `forge build` and after `scripts/demo.sh` (or the Deploy/Ship scripts).
// Vercel builds from this snapshot; it never needs Foundry or a connection to Anvil.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = join(here, "..", "..", "contracts");
const out = join(here, "..", "generated");
const chainId = process.env.NEXT_PUBLIC_CHAIN_ID ?? "130";
mkdirSync(out, { recursive: true });

const artifacts = {
  GlideLens: "GlideLens.sol/GlideLens.json",
  GlideSwapVMRouter: "GlideSwapVMRouter.sol/GlideSwapVMRouter.json",
  GlideHook: "GlideHook.sol/GlideHook.json",
  Aqua: "Aqua.sol/Aqua.json",
  PoolSwapTest: "PoolSwapTest.sol/PoolSwapTest.json",
};

let ts = "// generated by scripts/sync.mjs, do not edit\n";
for (const [name, rel] of Object.entries(artifacts)) {
  const path = join(contracts, "out", rel);
  if (!existsSync(path)) {
    console.error(`missing ${path}; run 'forge build' in contracts/ first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  ts += `export const ${name}Abi = ${JSON.stringify(abi)} as const;\n`;
}
const deployments = {};
const dir = join(contracts, "deployments");
const path = join(dir, `${chainId}.json`);
if (!existsSync(path)) throw new Error(`Missing ${path}; run contracts/scripts/setup.sh first.`);
deployments[chainId] = JSON.parse(readFileSync(path, "utf8"));
if (deployments[chainId].chainId !== Number(chainId)) throw new Error("Deployment chain ID does not match the selected chain.");
writeFileSync(join(out, "abis.ts"), ts);
writeFileSync(join(out, "deployments.json"), JSON.stringify(deployments, null, 2));
const positionPath = join(dir, `position-${chainId}.json`);
const positions = existsSync(positionPath) ? { [chainId]: JSON.parse(readFileSync(positionPath, "utf8")) } : {};
writeFileSync(join(out, "positions.json"), JSON.stringify(positions, null, 2) + "\n");
console.log(`synced ${Object.keys(artifacts).length} ABIs and deployment for chain ${chainId}; review generated/ before publishing`);
