// Copies contract ABIs and the local deployment files from ../contracts into ./generated.
// Run after `forge build` and after `scripts/demo.sh` (or the Deploy/Ship scripts).
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = join(here, "..", "..", "contracts");
const out = join(here, "..", "generated");
mkdirSync(out, { recursive: true });

const artifacts = {
  GlideLens: "GlideLens.sol/GlideLens.json",
  GlideSwapVMRouter: "GlideSwapVMRouter.sol/GlideSwapVMRouter.json",
  GlideHook: "GlideHook.sol/GlideHook.json",
  Aqua: "Aqua.sol/Aqua.json",
  PoolSwapTest: "PoolSwapTest.sol/PoolSwapTest.json",
};

let ts = "// generated by scripts/sync.mjs, do not edit\n";
for (const [name, rel] of Object.entries(artifacts)) {
  const path = join(contracts, "out", rel);
  if (!existsSync(path)) {
    console.error(`missing ${path}; run 'forge build' in contracts/ first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  ts += `export const ${name}Abi = ${JSON.stringify(abi)} as const;\n`;
}
writeFileSync(join(out, "abis.ts"), ts);

const deployments = {};
const positions = {};
const dir = join(contracts, "deployments");
if (existsSync(dir)) {
  for (const f of readdirSync(dir)) {
    const m = f.match(/^(position-)?(\d+)\.json$/);
    if (!m) continue;
    const json = JSON.parse(readFileSync(join(dir, f), "utf8"));
    (m[1] ? positions : deployments)[m[2]] = json;
  }
}
writeFileSync(join(out, "deployments.json"), JSON.stringify(deployments, null, 2));
writeFileSync(join(out, "positions.json"), JSON.stringify(positions, null, 2));
console.log(`synced ${Object.keys(artifacts).length} ABIs, ${Object.keys(deployments).length} deployment(s), ${Object.keys(positions).length} position(s)`);
